swagger: '2.0'
info:
    title: Riidepood
    version: 1.0.0
    description: hinda riideid ja pritsi tatti
paths:
    /products:
        get:
            tags:
                - Product
            responses:
                '200':
                    description: Returns a list of products
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            - Jeans
                            - T-Shirts
                            - Jackets
            summary: Get all the clothing in the API
            description: Returns all products that are registered in API
        post:
            tags:
                - Product
            parameters:
                -
                    name: body
                    description: The <product> that is to be created
                    schema:
                        $ref: '#/definitions/new-Product'
                    in: body
                    required: true
            responses:
                '201':
                    description: Send 201 when <Product> is successfully added to the database
                    schema:
                        $ref: '#/definitions/new-Product'
                '400':
                    description: Send 400 when the new <Product> has no name or price and if the price is not a number.
                    schema:
                        $ref: '#/definitions/Error'
            summary: Create a new product into the app
            description: 'Creates a new product instance with its required details, for further usage.'
    '/products/{ProductID}':
        get:
            tags:
                - Product
            responses:
                '200':
                    description: Returns all details of the given product
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        Singular product:
                            ProductID: 76be1daf-cec2-11f0-b43f-901b0eec5991
                            Name: Shirt
                            Price: 13.44
                            createdAt: '2025-12-01T16:31:14.000Z'
                            updatedAt: '2025-12-01T16:31:14.000Z'
                '404':
                    description: Given <product> instance could not been found
                    schema:
                        $ref: '#/definitions/Error'
            description: Will return all details of a given product based on the given product ID
        put:
            tags:
                - Product
            parameters:
                -
                    name: body
                    description: Contains new data to be changed in the specified <product>
                    schema:
                        $ref: '#/definitions/new-Product'
                    in: body
                    required: true
            responses:
                '201':
                    description: Returns 201 upon successful modification of <product>
                    schema:
                        $ref: '#/definitions/new-Product'
                    examples:
                        application/json:
                            -
                                Name: x
                                Price: 28.1
                                Image: t
                        Only Name:
                            -
                                Name: x0
                        Only Price:
                            -
                                Price: 47.4
                        Only Image:
                            -
                                Image: r2q
                '400':
                    description: Returns 400 when the given <Product> has not been given new parameters.
                    schema:
                        $ref: '#/definitions/Error'
                    examples:
                        application/json:
                            -
                                error: The given parameters have not changed from the original
                '404':
                    description: Given <product> instance has not been found.
                    schema:
                        $ref: '#/definitions/Error'
                    examples:
                        application/json:
                            -
                                error: Product has not been found
            summary: Modifies given product instance
            description: Changes the details of a given product instance if parameters have been inserted.
        delete:
            tags:
                - Product
            parameters:
                -
                    name: ProductID
                    description: ID of the given product
                    in: path
                    required: true
                    type: string
            responses:
                '204':
                    description: The given product instance has been succesfully deleted
                    schema:
                        $ref: '#/definitions/Delete-Product'
                '404':
                    description: The given product instance has not been found
                    schema:
                        $ref: '#/definitions/Error'
            summary: Deletes the product instance
            description: Takes a products ID as an argument and deletes the given <product> instance from the database
        parameters:
            -
                name: ProductID
                description: Product instance database ID
                in: path
                required: true
                type: string
    /category:
        post:
            parameters:
                -
                    name: body
                    schema:
                        $ref: '#/definitions/new-category'
                    in: body
                    required: true
            responses:
                '201':
                    description: Created new Product Category
                '400':
                    description: Send 400 when missing some parameter.
                    schema:
                        $ref: '#/definitions/Error'
                '404':
                    description: Send 404 when paramets are invalid or missing
                    schema:
                        $ref: '#/definitions/Error'
    /descriptions:
        post:
            parameters:
                -
                    name: body
                    description: The description to be created
                    schema:
                        $ref: '#/definitions/new-product-description'
                    in: body
                    required: true
            responses:
                '201':
                    description: Description has been successfully created
                    schema:
                        $ref: '#/definitions/new-product-description'
                    examples:
                        application/json:
                            -
                                Material: material
                                Color: uno
                                Size: 3x
                '400':
                    description: Returns an error if any params are missing or invalid
                    schema:
                        $ref: '#/definitions/Error'
            summary: Creates a description for a product
            description: 'Creates description with material, color, size'
    '/descriptions/{DescriptionID}':
        post:
            parameters:
                -
                    name: body
                    schema:
                        $ref: '#/definitions/new-product-description'
                    in: body
                    required: true
            responses:
                '201':
                    schema:
                        $ref: '#/definitions/new-product-description'
definitions:
    Error:
        title: Root Type for Error
        description: ''
        type: object
        properties:
            error:
                type: string
        example:
            error: Error message
    new-Product:
        title: Root Type for new-CLothing-Item
        description: 'Contains name, price and image parameters for product instance'
        required:
            - Name
            - Price
        type: object
        properties:
            Name:
                type: string
            Price:
                format: double
                type: number
                readOnly: false
            Image:
                type: string
        example:
            Name: NewProductName
            Price: 50
            Image: NewProductImage
    Delete-Product:
        title: Root Type for Delete-Product
        description: ''
        type: object
        properties:
            ProductID:
                type: string
        example:
            ProductID: 019adf6b-d945-7ac1-bf4f-280c7c4236e8
    new-category:
        title: Root Type for new-category
        description: New product category
        type: object
        properties:
            Name:
                type: string
            Image:
                type: string
        example:
            Name: Example name
            Image: ImageUrl
    new-product-description:
        description: ''
        required:
            - ProductID
            - Material
            - Color
            - Size
        type: object
        properties:
            ProductID:
                description: ''
                type: string
            Material:
                description: ''
                type: string
            Color:
                description: ''
                type: string
            Size:
                description: ''
                type: string
        example:
            ProductID: 019b0891-7288-7b80-b599-a0d0fcf087a4
            Material: NewMaterialName
            Color: NewColor
            Size: NewSize
