swagger: '2.0'
info:
    title: Riidepood
    version: 1.0.0
    description: hinda riideid ja pritsi tatti
paths:
    /product:
        get:
            tags:
                - Product
            responses:
                '200':
                    description: Returns a list of products
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            - Jeans
                            - T-Shirts
                            - Jackets
            summary: Get all the clothing in the API
            description: Returns all products that are registered in API
        post:
            tags:
                - Product
            parameters:
                -
                    name: body
                    description: The <product> that is to be created
                    schema:
                        $ref: '#/definitions/new-Product'
                    in: body
                    required: true
            responses:
                '201':
                    description: Send 201 when <Product> is successfully added to the database
                    schema:
                        $ref: '#/definitions/new-Product'
                '400':
                    description: Send 400 when the new <Product> has no name or price and if the price is not a number.
                    schema:
                        $ref: '#/definitions/Error'
            summary: Create a new product into the app
            description: 'Creates a new product instance with its required details, for further usage.'
    '/product/{ProductID}':
        get:
            tags:
                - Product
            responses:
                '200':
                    description: Returns all details of the given product
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        Singular product:
                            ProductID: 76be1daf-cec2-11f0-b43f-901b0eec5991
                            Name: Shirt
                            Price: 13.44
                            createdAt: '2025-12-01T16:31:14.000Z'
                            updatedAt: '2025-12-01T16:31:14.000Z'
                '404':
                    schema:
                        $ref: '#/definitions/Error'
            description: Will return all details of a given product based on the given product ID
definitions:
    Error:
        title: Root Type for Error
        description: ''
        type: object
        properties:
            error:
                type: string
        example:
            error: Error message
    new-Product:
        title: Root Type for new-CLothing-Item
        description: 'Contains name, price and image parameters for product instance'
        required:
            - Name
            - Price
        type: object
        properties:
            Name:
                type: string
            Price:
                format: double
                type: number
                readOnly: false
            Image:
                type: string
        example:
            Name: NewProductName
            Price: NewProductPrice
            Image: NewProductImage
